### ISSUE TITLE
cant compile latest

### ISSUE THREAD

**Issue by solnyszczko** [sparr/ascii-factory#1]
error[E0583]: file not found for module `visibility`
  --> src/lib.rs:18:1
   |
18 | mod visibility;
   | ^^^^^^^^^^^^^^^
   |
   = help: to create the module `visibility`, create file "src/visibility.rs" or "src/visibility/mod.rs"

error[E0432]: unresolved import `crate::visibility::Viewshed`
 --> src/player.rs:7:5
  |
7 | use crate::visibility::Viewshed;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Viewshed` in `visibility`

error[E0432]: unresolved imports `visibility::reveal_map`, `visibility::update_viewsheds`
  --> src/lib.rs:19:18
   |
19 | use visibility::{reveal_map, update_viewsheds};
   |                  ^^^^^^^^^^  ^^^^^^^^^^^^^^^^ no `update_viewsheds` in `visibility`
   |                  |
   |                  no `reveal_map` in `visibility`

error[E0599]: the method `before` exists for fn item `fn(ResMut<'a, BevyBracket>, Query<'b, 'c, (..., ...), ...>) {handle_input}`, but its trait bounds were not satisfied
  --> src/lib.rs:47:30
   |
47 |                 handle_input.before(wrap_position),
   |                              ^^^^^^ method cannot be called due to unsatisfied trait bounds
   |

**Comment by sparr** [comment]
I forgot to add the new file. Good catch. Thanks.
